// Package main regenerates the API coverage table in README.md from
// contract_test/contract_test.go's operations table, cross-referenced
// against the Prolific OpenAPI spec for each operation's method and path.
//
// Usage:
//
//	go run ./scripts/readme-coverage
package main

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

const (
	specURL          = "https://docs.prolific.com/openapi.yaml"
	contractTestPath = "contract_test/contract_test.go"
	readmePath       = "README.md"
	coverageStartTag = "<!-- API-COVERAGE:START (generated by `make readme-coverage`, do not edit by hand) -->"
	coverageEndTag   = "<!-- API-COVERAGE:END -->"
)

// entry is one row of the operations table: an operationId, the section
// comment it falls under, and either the Go client method that covers it or
// a skip reason explaining why it doesn't.
type entry struct {
	section      string
	operationID  string
	clientMethod string // empty if skipped
	skipTag      string // OUTOFSCOPE, SPECMISMATCH, HARNESSGAP, or "" if covered
	skipReason   string
}

type specOp struct {
	method string
	path   string
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}

func run() error {
	entries, err := parseOperations(contractTestPath)
	if err != nil {
		return fmt.Errorf("parsing operations table: %w", err)
	}

	specOps, err := loadSpecOperations()
	if err != nil {
		return fmt.Errorf("loading OpenAPI spec: %w", err)
	}

	table, err := renderTable(entries, specOps)
	if err != nil {
		return fmt.Errorf("rendering table: %w", err)
	}

	if err := spliceIntoReadme(table); err != nil {
		return fmt.Errorf("updating README.md: %w", err)
	}

	fmt.Printf("Updated %s with %d operations.\n", readmePath, len(entries))
	return nil
}

var (
	reSection    = regexp.MustCompile(`^\t// ([A-Z].*)$`)
	reOpID       = regexp.MustCompile(`operationID:\s*"([^"]+)"`)
	reSkip       = regexp.MustCompile(`skip:\s*"((?:[^"\\]|\\.)*)"`)
	reClientCall = regexp.MustCompile(`\bc\.([A-Z]\w+)\(`)
)

// parseOperations extracts the operations table from contract_test.go by
// scanning for top-level `{operationID: ...}` entries (tracking brace depth
// so multi-line `call: func(...) {...}` closures don't get split), and the
// `// Section` comments that group them.
func parseOperations(path string) ([]entry, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	lines := strings.Split(string(data), "\n")

	start, end := -1, -1
	for i, line := range lines {
		if strings.HasPrefix(line, "var operations = []operation{") {
			start = i + 1
			continue
		}
		if start != -1 && line == "}" {
			end = i
			break
		}
	}
	if start == -1 || end == -1 {
		return nil, fmt.Errorf("could not find operations table bounds in %s", path)
	}

	var entries []entry
	section := ""
	i := start
	for i < end {
		line := lines[i]

		if m := reSection.FindStringSubmatch(line); m != nil {
			section = m[1]
			i++
			continue
		}

		if !strings.Contains(line, "operationID:") {
			i++
			continue
		}

		// Accumulate lines until braces balance back to zero, to capture
		// multi-line call: func(...) {...}} entries as a single chunk.
		chunk := line
		depth := strings.Count(line, "{") - strings.Count(line, "}")
		for depth > 0 {
			i++
			chunk += "\n" + lines[i]
			depth += strings.Count(lines[i], "{") - strings.Count(lines[i], "}")
		}
		i++

		opIDMatch := reOpID.FindStringSubmatch(chunk)
		if opIDMatch == nil {
			continue
		}
		e := entry{section: section, operationID: opIDMatch[1]}

		if skipMatch := reSkip.FindStringSubmatch(chunk); skipMatch != nil {
			reason := skipMatch[1]
			if tag, rest, ok := strings.Cut(reason, ": "); ok {
				e.skipTag, e.skipReason = tag, rest
			} else {
				e.skipReason = reason
			}
		} else if callMatch := reClientCall.FindStringSubmatch(chunk); callMatch != nil {
			e.clientMethod = callMatch[1]
		}

		entries = append(entries, e)
	}

	// Belt-and-braces: if the regex-based scan above ever fails to match an
	// operationID it saw the literal text for, don't silently ship a table
	// that's missing entries — fail loudly instead.
	rawCount := strings.Count(strings.Join(lines[start:end], "\n"), "operationID:")
	if rawCount != len(entries) {
		return nil, fmt.Errorf(
			"parsed %d entries but found %d \"operationID:\" occurrences in the table — a regex likely failed to match one",
			len(entries), rawCount)
	}

	return entries, nil
}

// loadSpecOperations always downloads the live spec fresh — matching
// contract_test.go's own TestMain, which never trusts a cached copy — and
// maps each operationId to its HTTP method and path.
func loadSpecOperations() (map[string]specOp, error) {
	data, err := downloadSpec()
	if err != nil {
		return nil, err
	}

	var spec struct {
		Paths map[string]map[string]struct {
			OperationID string `yaml:"operationId"`
		} `yaml:"paths"`
	}
	if err := yaml.Unmarshal(data, &spec); err != nil {
		return nil, fmt.Errorf("parsing spec YAML: %w", err)
	}

	ops := make(map[string]specOp)
	for path, methods := range spec.Paths {
		for method, op := range methods {
			if op.OperationID != "" {
				ops[op.OperationID] = specOp{method: strings.ToUpper(method), path: path}
			}
		}
	}
	return ops, nil
}

func downloadSpec() ([]byte, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, specURL, nil)
	if err != nil {
		return nil, err
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("GET %s: %w", specURL, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("GET %s: unexpected status %s", specURL, resp.Status)
	}
	return io.ReadAll(resp.Body)
}

func renderTable(entries []entry, specOps map[string]specOp) (string, error) {
	var missing []string
	for _, e := range entries {
		if _, ok := specOps[e.operationID]; !ok {
			missing = append(missing, e.operationID)
		}
	}
	if len(missing) > 0 {
		return "", fmt.Errorf(
			"%d operationId(s) in contract_test.go's table are not in the live spec (stale entries? see DCT-261): %s",
			len(missing), strings.Join(missing, ", "))
	}

	var b strings.Builder
	b.WriteString("Operations are grouped as they appear in [`contract_test/contract_test.go`](contract_test/contract_test.go), ")
	b.WriteString("which validates every entry marked ✅ against the live Prolific OpenAPI spec on every test run.\n\n")

	sections := sectionOrder(entries)
	for _, section := range sections {
		b.WriteString(fmt.Sprintf("<details>\n<summary><strong>%s</strong></summary>\n\n", section))
		b.WriteString("| Operation | Method | Path | Coverage |\n")
		b.WriteString("|---|---|---|---|\n")
		for _, e := range entries {
			if e.section != section {
				continue
			}
			op := specOps[e.operationID]
			b.WriteString(fmt.Sprintf("| `%s` | %s | `%s` | %s |\n",
				e.operationID, op.method, op.path, statusCell(e)))
		}
		b.WriteString("\n</details>\n\n")
	}
	return strings.TrimRight(b.String(), "\n") + "\n", nil
}

func statusCell(e entry) string {
	switch {
	case e.clientMethod != "":
		return fmt.Sprintf("✅ `%s`", e.clientMethod)
	case e.skipTag == "OUTOFSCOPE":
		return "➖ Not exposed in the CLI"
	case e.skipTag == "HARNESSGAP":
		return "⚠️ Covered, not spec-validated — test harness limitation"
	case e.skipTag == "SPECMISMATCH":
		return "❌ Known mismatch — needs a fix"
	default:
		return e.skipReason
	}
}

// sectionOrder returns each distinct section name in first-seen order.
func sectionOrder(entries []entry) []string {
	seen := make(map[string]bool)
	var order []string
	for _, e := range entries {
		if !seen[e.section] {
			seen[e.section] = true
			order = append(order, e.section)
		}
	}
	return order
}

func spliceIntoReadme(table string) error {
	data, err := os.ReadFile(readmePath)
	if err != nil {
		return err
	}
	content := string(data)

	startIdx := strings.Index(content, coverageStartTag)
	endIdx := strings.Index(content, coverageEndTag)
	if startIdx == -1 || endIdx == -1 || endIdx < startIdx {
		return fmt.Errorf("could not find %q / %q markers in %s", coverageStartTag, coverageEndTag, readmePath)
	}

	before := content[:startIdx+len(coverageStartTag)]
	after := content[endIdx:]
	newContent := before + "\n\n" + table + "\n" + after

	return os.WriteFile(readmePath, []byte(newContent), 0o600)
}
