name: "wiki-watcher"
on: [gollum]

jobs:
  watch:
    name: "Watcher"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wiki Watcher
        uses: benmatselby/gollum-page-watcher-action@v1.9.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
