name: Main

permissions:
  contents: write
  issues: write
  pull-requests: write

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  QualityChecks:
    name: Quality Checks
    uses: ./.github/workflows/go.yml
    secrets: inherit

  Release:
    name: Create Release
    needs: [QualityChecks]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v6
        with:
          branch: main
          semantic_version: 24.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
