name: Release

on:
  release:
    types: [published]
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Determine tag
        id: tag
        run: |
          TAG="${{ inputs.tag || github.event.release.tag_name }}"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Set up Go
        uses: actions/setup-go@v6.2.0
        with:
          go-version: 1.26.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v6
        with:
          ref: ${{ steps.tag.outputs.tag }}

      - name: Get dependencies
        run: |
          make install

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make clean

          GOOSARCHES=(
            darwin/amd64
            darwin/arm64
            freebsd/amd64
            freebsd/386
            linux/arm
            linux/arm64
            linux/amd64
            linux/386
            windows/amd64
            windows/386
          )

          for GOOSARCH in "${GOOSARCHES[@]}"; do
            GOOS=${GOOSARCH%/*}
            ARCH=${GOOSARCH#*/}

            echo "\n\nBuilding binary for ${GOOS}/${ARCH}\n"

            GIT_RELEASE=${{ steps.tag.outputs.tag }} GOOS=${GOOS} GOARCH=${ARCH} make static-named
          done

          gh release upload ${{ steps.tag.outputs.tag }} build/*

